### ISSUE TITLE
What about Table widget?

### ISSUE THREAD

**Issue by hyorigo** [charmbracelet/bubbles#12]
Hi guys,

Do you have any plan to implement Table widgets for Bubble Tea? Or a little hack with the "Viewpoint" widget to support simple tables?

Thanks for your great works!

**Comment by meowgorithm** [comment]
Hi! Tables are pretty simple in Bubble Tea since they're just strings. Here's some [example code](https://github.com/charmbracelet/bubbletea/blob/master/examples/glamour/main.go) we just pushed that shows how you can render a table in a viewport using [Glamour](http://github.com/charmbracelet/glamour).

[![Glamour Example](https://user-images.githubusercontent.com/25087/96778440-b74bae80-13b9-11eb-9995-b969fbfbe3fd.gif)](https://github.com/charmbracelet/bubbletea/blob/master/examples/glamour/main.go)

That said, we do plan in making an interactive table widget. In the meantime, here's some example code for an interactive table using [olekukonko/tablewriter](https://github.com/olekukonko/tablewriter):

![Interactive Table Example](https://user-images.githubusercontent.com/25087/96778877-448f0300-13ba-11eb-99aa-ef8ecbc8f27f.gif)

```go
package main

import (
	"fmt"
	"os"
	"strings"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/muesli/termenv"
	"github.com/olekukonko/tablewriter"
)

var (
	term = termenv.ColorProfile()

	// The data for our table
	data = [][]string{
		{"A Fistful of Dollars", "Western", "1964"},
		{"For a few Dollars More", "Western", "1965"},
		{"The Good, the Bad and the Ugly", "Western", "1966"},
	}
)

type model int

func (m model) Init() tea.Cmd {
	return nil
}

func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch msg.String() {
		case "q", "ctrl+c":
			return m, tea.Quit
		case "k", "up":
			m--
			if int(m) < 0 {
				m = model(len(data) - 1)
			}
		case "j", "down":
			m++
			if int(m) > len(data) {
				m = 0
			}
		}
	}
	return m, nil
}

func (m model) View() string {
	s := strings.Builder{}

	// Set table header
	table := tablewriter.NewWriter(&s)
	table.SetHeader([]string{"Name", "Genre", "Year"})

	// Add data to table
	for i, v := range data {
		if int(m) == i {
			// Color active item
			c := tablewriter.Colors{tablewriter.FgBlackColor, tablewriter.BgWhiteColor}
			var colors []tablewriter.Colors
			for range v {
				colors = append(colors, c)
			}
			table.Rich(v, colors)
		} else {
			table.Append(v)
		}

	}

	table.Render()
	s.WriteString(termenv.String(" ↑/↓: Choose • q: Quit").Foreground(term.Color("241")).String())
	return s.String()
}

func main() {
	if err := tea.NewProgram(model(0)).Start(); err != nil {
		fmt.Printf("Oh no! %v\n", err)
		os.Exit(1)
	}
}
```

There are plenty of other table drawing packages that would work too.

**Comment by hyorigo** [comment]
Thanks for your help!

Fix a typo in the code snippet:
```go
			if int(m) > len(data) {
				m = 0
			}
```
->
```go
			if int(m) >= len(data) {
				m = 0
			}
```

However, I do hope you guys can support a formal table widget like the viewport in Glamour, the border lines of olekukonko/tablewriter looks really awkward.

**Comment by meowgorithm** [comment]
Thanks for that. Glamour actually uses olekukonko/tablewriter but with custom glyphs for borders. [Here’s the implementation](https://github.com/charmbracelet/glamour/blob/8d4e3f0692f80267a1896eb53455c024865c729b/ansi/table.go#L58) and [here are the glyphs](https://github.com/charmbracelet/glamour/blob/master/styles/dark.json#L183).

Anyway, I'll let you know when we build a component for this; it will more than likely be based on the code above.

**Comment by rverton** [comment]
Is there a simple way to combine this example with a pager or the possibility to scroll the content of the table (and keep the header fixed to top) in AltMode? Because if there are too many items in the table, the selection/display is broken.

**Comment by maaslalani** [comment]
Table widget is now implemented https://github.com/charmbracelet/bubbles/tree/master/table

**Comment by maaslalani** [comment]
@hyorigo Introduction is here and demo gif is now in the README https://github.com/charmbracelet/bubbles/releases/tag/v0.14.0!
