### ISSUE TITLE
List: Gap for Title/Spinner always present, even though both is disabled

### ISSUE THREAD

**Issue by toadle** [charmbracelet/bubbles#130]
List will always keep this gap open, even if `Title` and `Spinner` are disabled.

<img width="431" alt="Bildschirmfoto 2022-03-28 um 22 39 46" src="https://user-images.githubusercontent.com/115103/160486140-7213d99e-2934-43f2-b1fb-f93066f5dcf2.png">

That makes it less flexible to use. It should be able to appear completely compact, if you choose to. 

- [ ] Don't reserve space if nothing (title or spinner) are shown here
- [ ] Preferably: Add a `SetShowSpinner`-func that lets you disable it

**Comment by meowgorithm** [comment]
Hi there! You should be able to remove the title entirely with [`SetShowTitle`](https://pkg.go.dev/github.com/charmbracelet/bubbles@v0.10.3/list#Model.SetShowTitle).

If you’re working off the [`list-fancy`](https://github.com/charmbracelet/bubbletea/blob/master/examples/list-fancy/main.go) example you can additionally remove the the padding around the list [`here`](https://github.com/charmbracelet/bubbletea/blob/master/examples/list-fancy/main.go#L16).

**Comment by toadle** [comment]
I did. The space stays. 

The above is the result of: 
```
	list.SetShowHelp(false)
	list.SetShowStatusBar(false)
	list.SetShowTitle(false)
	list.Select(-1)
```

**Comment by usrme** [comment]
Terribly sorry to unearth this already closed issue, but this fix inadvertently broke something for me, which I know is wholly my own doing due to inexperience and poor design. Regardless, I was wondering if someone could perhaps point me towards a solution or way of seeing things where I could occupy the same space as the filtering input, but have it be styled differently and have it do different things?
