### ISSUE TITLE
Feat(textinput): ctrl + left/right bindings for word jumping

### ISSUE THREAD

**Issue by NiloCK** [charmbracelet/bubbles#150]
Expected behaviours:
- ctrl+left/right: move one word left/right
- ctrl+backspace/delete: delete one word left/right

The above are default behaviours in most linux and windows text editing environments. It would be nice to have them respected by the `textinput`.

Having spent 3 minutes reading the textinput.Update, I see that a lot of care has gone into handling some specific cases of input for the `textinput` bubble.

Having spent 5 minutes working in a local fork, I see that keystrokes do not come with `Ctrl` modifiers in the same way as `Alt` modifiers, and that the specific `KeyCtrlN` values are for letters only, and do not include the needed values for the above updates.

Is it correct to assume that there is some technical reason why `Ctrl` hasn't received a similar treatment as `Alt`?

Is access to the state of `ctrl` being worked on?

Thanks

**Comment by meowgorithm** [comment]
Hi! There are a few questions here so I'm dividing my response into sections accordingly.

## Ctrl + Arrows

Good catch! We should absolutely add support <kbd>ctrl+arrows</kbd> and word-jumping as soon as https://github.com/charmbracelet/bubbletea/pull/292 is merged. That PR adds support for <kbd>ctrl+arrow</kbd> mappings, among another things.

## Ctrl versus Alt

You're correct, <kbd>ctrl</kbd> is treated differently than <kbd>alt</kbd> for technical reasons, and that's actually why we can't provide a mapping for <kbd>ctrl+backspace</kbd> and <kbd>ctrl+delete</kbd>. <kbd>ctrl</kbd> modifiers in the terminal originally existed to send "control characters" through the wire and manipulate the terminal, which is mostly why they're so limited. For example <kbd>backspace</kbd> and <kbd>ctrl+h</kbd> both send a backspace to the terminal, and there isn't much way around that.

`CSI u` (see https://github.com/charmbracelet/bubbletea/issues/293) solves for this, however it's not particularly well supported and, for now, not a viable solution. It's also possible to get an enormous amount of insight into keyboard input on Windows, however we don't plan on implementing that as it's not cross-platform.

Anyway, all this said, we _have_ considered separating out <kbd>shift</kbd>, <kbd>ctrl</kbd>, and <kbd>alt</kbd> modifiers so that they’d be more like `alt` from an API perspective. Even if we do that however, those modifiers would not be available for every single key (<kbd>alt</kbd> included).

**Comment by NiloCK** [comment]
Appreciate the quick info! I am **unsurprised** that there are deep legacy issues at hand with respect to handling keyboard input in the terminal.

Happy to see progress on the arrows.

**Comment by bashbunni** [comment]
@meowgorithm heyhey looks like the PR you mentioned with the requested changes was merged, can I go ahead and close this issue?

**Comment by meowgorithm** [comment]
@bashbunni Heya! We added the necessary key binding support in Bubble Tea to make this possible however we still need to add bindings to textinput for <kbd>ctrl</kbd> + left/right for word jumping as described above. So what should happen (in this order is):

1. After the next Bubble Tea release
2. Bump the Bubble Tea dep in Bubbles
3. And add the above bindings to `textinput`

**Comment by tartavull** [comment]
Is this still in progress? 

I'm trying to either use shift+enter to "submit" the text input value. Or use enter for "submission" and shift+enter for a new line. Is there a way to achieve this with the current implementation? I've tried a few things but nothing worked.

**Comment by maaslalani** [comment]
> Is this still in progress?
> 
> I'm trying to either use shift+enter to "submit" the text input value. Or use enter for "submission" and shift+enter for a new line. Is there a way to achieve this with the current implementation? I've tried a few things but nothing worked.

Hey @tartavull We are planning to add a way to support `shift+enter` support to Bubbletea! Currently there isn't a way to recognize this binding since there is limited support in terminals but with the Kitty Keyboard Protocol which is supported in alacritty, kitty, wezterm, etc... we can support it.

**Comment by maaslalani** [comment]
Fixed by https://github.com/charmbracelet/bubbles/pull/387
