### ISSUE TITLE
list: slot above populated view

### ISSUE THREAD

**Issue by nicolasparada** [charmbracelet/bubbles#80]
I'm trying to use the list bubble to render a table.
I am doing it with a custom delegate, but I'am having problems to render the table header (column names) since I cannot place it where I want.

So far I can disable the title, status bar and filter and also remove paddings to insert the table header on top of the whole list, but that is not ideal.

Having a "slot" where I could place some content just above the populated view would be ideal.

**Comment by meowgorithm** [comment]
Hey, @nicolasparada! Just to get a better understanding, what's the benefit in your case to using the list view to render a table versus making one from scratch. Pagination?

**Comment by nicolasparada** [comment]
Yes, to reuse pagination, item selection, help and all of that :)

**Comment by nicolasparada** [comment]
But it also could make sense to create a new "table" bubble https://github.com/charmbracelet/bubbles/issues/12

**Comment by meowgorithm** [comment]
It would be nice to make a proper table bubble, though it totally makes sense as to why you're using the list here for now. On that note, it maybe even make sense to implement the table Bubble on top of the list (sort of what https://github.com/charmbracelet/bubbles/issues/12#issuecomment-829609373 is asking for).

In the meantime, one option would be to expose the List Bubble’s various subviews (title view, content view, and so on) so that you could sidestep the main `View()` function and compose your own list view. That would have the added benefit of allowing users to rearrange items in the List Bubble, too.

@muesli was also toying with the idea of providing a sort of top-level delegate that could compose the components in a similar fashion, thought it would _probably_ require a bit more boilerplate.

**Comment by maaslalani** [comment]
We now have a proper table bubble: https://github.com/charmbracelet/bubbles/tree/master/table

@nicolasparada If you still think this issue is valid please feel free to reopen.

**Comment by nicolasparada** [comment]
Awesome ❤️
